brew install aria2
brew install cocoapods
brew install fd
brew install ffmpeg
brew install flutter
brew install go
brew install lua
brew install neovim
brew install pyenv
brew install scrcpy
brew install starship
brew install tmux
brew install wget
brew install z.lua
brew install zsh-autosuggestions
brew install zsh-history-substring-search
brew install zsh-syntax-highlighting
brew install 1password
brew install alfred
brew install android-studio
brew install baidunetdisk
brew install cmake
brew install emacs
brew install fontforge
brew install google-chrome
brew install iina
brew install istat-menus
brew install mono-mdk-for-visual-studio
brew install tunnelblick
brew install visual-studio
brew install visual-studio-code
