#!/bin/bash

# list of network
list(){
  networksetup -listallnetworkservices
}

# off
off(){
  networksetup -setwebproxystate Wi-Fi off
  networksetup -setsocksfirewallproxystate Wi-Fi off
  networksetup -setsecurewebproxystate Wi-Fi off
}

# on
networksetup -setwebproxystate Wi-Fi on
networksetup -setwebproxy Wi-Fi 127.0.0.1 7890
networksetup -setsecurewebproxystate Wi-Fi on
networksetup -setsecurewebproxy Wi-Fi 127.0.0.1 7890
networksetup -setsocksfirewallproxystate Wi-Fi on
networksetup -setsocksfirewallproxy Wi-Fi 127.0.0.1 7891

sudo nohup /Users/albert/go/bin/clash -f /Users/albert/.config/clash/Global.yaml  > /dev/null 2>&1 &
